version: '3'
services:
  goodneighbourbackend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=saireddypadala
      - POSTGRES_USER=saireddypadala
      - POSTGRES_PASSWORD=Happylife@143
    depends_on:
      - db
    networks:
      - spring-postgres

  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=saireddypadala
      - POSTGRES_USER=saireddypadala
      - POSTGRES_PASSWORD=Happylife@143
    expose:
      - "5432"

volumes:
  db-data:

networks:
  spring-postgres:
